services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev  # Change to 'runner' for production
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
